#pragma once
#ifndef MYIMGPROC_H
#define MYIMGPROC_H

#include <cstdio>
#include <iostream>
#include <sstream>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/videoio.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/video.hpp>
#include <opencv2/opencv.hpp>

#include "Maze.h"

using namespace cv;
using namespace std;

class Myimgproc
{
private:
	static Mat fgMaskMOG2; //fg mask fg mask generated by MOG2 method
	static Mat img_tracking;
	static Ptr<BackgroundSubtractor> pMOG2; //MOG2 Background subtractor

	//erosion / dilation window size
	static const int erosion_size = 3;
	static const int dilation_size = 8;

	//used by findContours method
	static vector<vector<Point>> contours;
	static vector<Vec4i> hierarchy;

	//used to extract maze lines
	static Mat src_HSV;
	static Mat dst;

public:
	/**/
	static void init();

	/*
	*Create all opencv windows to show results
	*/
	static void createAllWindows(void);


	/*  Get tank position
	*  mark it with contour
	*  uses background substraction algorithm
	*/
	static Point2i & processImages(Mat & frame);


	/*Extract maze lines from first image
	* and draw them
	*/
	static void draw_maze(Mat & frame);

	/**
	 * Scan 1st frame and create graph nodes
	 * makes graph with line crossing
		NOT YET IMPLEMENTED
	 */
	static void create_graph(Mat & frame);

	/**
	 * Scan 1st frame and create graph nodes
	 * makes graph with rect tiles (sliding window)
	 */
	static Maze * create_graph2();
	
	/**
	 *	for each rectangle
	 *	check if it intersects with maze line
	 *	return true if not intersect
	 */
	static bool check_empty(Rect & windows, Mat & frame);

	static Point2i middle_point(Rect & windows);

	//Point & find_middle_lane(pair<Point, Point> & current_line, vector<pair<Point, Point>> & line_cart);

};

void histogram_debug(void);

#endif // MYIMGPROC_H